version: "3"

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    command: make run
    restart: always
    env_file:
      - ./config/docker.env
    ports:
      - 8001:8000
    depends_on:
      - db

  db:
    image: edgedb/edgedb
    env_file:
      - ./config/docker.env
    ports:
      - 5656:5656
    volumes:
      - "./dbschema:/dbschema"

  cache:
    image: redis
    restart: unless-stopped
    env_file:
      - ./config/docker.env
    ports:
      - 6379:6379
    volumes:
      - ./.cache/redis/data:/data
    stdin_open: true

  cache-exporter:
    image: oliver006/redis_exporter
    ports:
      - 9121:9121
    environment:
      REDIS_ADDR: "cache:6379"
    links:
      - cache

  grafana:
    image: grafana/grafana:latest
    restart: unless-stopped
    environment:
      - GF_SECURITY_ADMIN_USER=dus
      - GF_SECURITY_ADMIN_PASSWORD=grafanaPwd_123
    ports:
      - 3000:3000
    volumes:
      - ./.cache/grafana:/var/lib/grafana

  prometheus:
    image: prom/prometheus
    volumes:
      - ./config/prometheus/:/etc/prometheus/
      - ./.cache/prometheus/:/prometheus
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.path=/prometheus"
      - "--web.console.libraries=/usr/share/prometheus/console_libraries"
      - "--web.console.templates=/usr/share/prometheus/consoles"
    ports:
      - 9090:9090
    restart: always
